CREATE TABLE `pick_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pickId` varchar(64) NOT NULL,
	`gameDate` varchar(16) NOT NULL,
	`playerId` int NOT NULL,
	`playerName` varchar(128) NOT NULL,
	`playerTeam` varchar(64) NOT NULL,
	`gameId` varchar(64) NOT NULL,
	`market` varchar(32) NOT NULL DEFAULT 'hrr',
	`recommendedLine` text NOT NULL,
	`confirmedOdds` int,
	`currentOdds` int,
	`edge` int,
	`matrixScore` int,
	`probability` int,
	`tier` varchar(8),
	`boardPhase` varchar(32) NOT NULL,
	`pickStatus` enum('preliminary','confirmed','evening_confirmed','early_locked','later_qualifier','voided') NOT NULL,
	`confirmedAt` timestamp,
	`voidedAt` timestamp,
	`voidReason` varchar(256),
	`actualValue` int,
	`result` enum('pending','hit','miss') NOT NULL DEFAULT 'pending',
	`gradedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pick_snapshots_id` PRIMARY KEY(`id`),
	CONSTRAINT `pick_snapshots_pickId_unique` UNIQUE(`pickId`)
);
