CREATE TABLE `pitcher_recommendation_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`gameDate` varchar(16) NOT NULL,
	`pitcherName` varchar(128) NOT NULL,
	`pitcherId` int,
	`pitcherTeam` varchar(8) NOT NULL,
	`opponentTeam` varchar(8) NOT NULL,
	`propType` enum('strikeouts','walks','outs','innings','hits_allowed','earned_runs') NOT NULL,
	`pitcherHand` enum('L','R','S') DEFAULT 'R',
	`umpire` varchar(128),
	`weather` varchar(256),
	`park` varchar(64),
	`bookOdds` int,
	`projection` int,
	`line` int,
	`result` enum('pending','hit','miss','ppd') NOT NULL DEFAULT 'pending',
	`actualValue` int,
	`disciplineEdge` int DEFAULT 0,
	`tms` int,
	`disciplineGrade` varchar(4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pitcher_recommendation_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `team_discipline_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`teamAbbr` varchar(8) NOT NULL,
	`teamName` varchar(64) NOT NULL,
	`season` int NOT NULL,
	`walkRatePct` int,
	`strikeoutRatePct` int,
	`chaseRatePct` int,
	`contactRatePct` int,
	`zoneContactPct` int,
	`swingStrikePct` int,
	`firstPitchSwingPct` int,
	`pitchesPerPA` int,
	`walkRateVsRHP` int,
	`walkRateVsLHP` int,
	`kRateVsRHP` int,
	`kRateVsLHP` int,
	`disciplineGrade` enum('A+','A','B','C','D') NOT NULL DEFAULT 'B',
	`disciplineScore` int NOT NULL DEFAULT 50,
	`walkTendencyScore` int DEFAULT 50,
	`strikeoutTendencyScore` int DEFAULT 50,
	`pitchCountTendencyScore` int DEFAULT 50,
	`patientScore` int DEFAULT 50,
	`aggressiveScore` int DEFAULT 50,
	`marketOverPerformScore` int DEFAULT 50,
	`marketUnderPerformScore` int DEFAULT 50,
	`walkBoostBps` int DEFAULT 0,
	`strikeoutBoostBps` int DEFAULT 0,
	`lastFetchedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `team_discipline_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `team_discipline_profiles_teamAbbr_unique` UNIQUE(`teamAbbr`)
);
